name: build dist

on:
  push:
  pull_request:

jobs:
  build:
    name: 'build Desktop on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, windows-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: apt update and install
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update

    - name: build
      run: ./gradlew build package

    - name: upload build failure logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-failure-logs-${{ matrix.os }}
        path: |
          kmdsp/build/reports/

    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: kmdsp-${{ matrix.os }}
        path: |
          kmdsp/build/outputs/apk/debug/*.apk
          kmdsp/build/outputs/bundle/release/*.aab
          kmdsp/build/dist/wasmJs/
          kmdsp/build/compose/binaries/main/deb/*.deb
          kmdsp/build/compose/binaries/main/dmg/*.dmg
          kmdsp/build/compose/binaries/main/msi/*.msi

    - name: deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.2
      if: contains(matrix.os, 'ubuntu')
      with:
        branch: gh-pages
        folder: kmdsp/build/processedResources/wasmJs/main
